### ISSUE TITLE
老铁

### ISSUE THREAD

**Issue by JGNS** [GuoZhaoHui628/AutoLayoutAll#5]
老铁，我看你选择的默认values是1dp=1px，而且那个文件中的单位不是px了，是dp。我的想法是，既然选择了750*1334.那默认的values，我可以直接把750*1334中的copy到默认values，相当于让默认的去匹配750*1334，这样ok吗。或者copy标准的720*1280，只是我这样做，默认values中的单位是px了，不知道会不会报错

**Comment by GuoZhaoHui628** [comment]
@JGNS 首先 我将默认的修改成 px ，主要是为了画UI xml时可以预览，当然你也可以换成 px 。然后 750×1334这个基准保本来就有一套分辨率，并不是算默认。默认的意思是对任何分辨率都适配，毕竟我们在 xml 画 UI 时还是使用的 x300 y300 这种既不是 px dp 的数值。所以你说的默认 values 中的单位是 px 你可以去看看，里面有一套本来就是这样的分辨率

**Comment by JGNS** [comment]
@GuoZhaoHui628 老铁没太明白你的意思。可能我没表述明白。我的意思是，我们已经建立了很多values文件夹了，适配了大部分的屏幕。但是一旦出现没有匹配到的分辨率，系统会从默认的values里读取。那么这个默认的vluaes里的值，应该是靠近720p/1080p的，(现在没有太次的手机了),那么我就想把720p当成默认，把720p文件夹直接copy进默认就行了。但是这样的话默认valus单位是px,不是dp

**Comment by GuoZhaoHui628** [comment]
@JGNS 没 不应该这样。对于这个默认value，我的理解是除了我们适配到的，除此之外的所有都是默认value。假设现在有三个用户手机都不在我们统计的value中，并且他们分辨率分别都不相同，如果我们不提供默认的value就有可能报错或者不适配，所以这样看来 这个 默认value并不固定，毕竟对刚才的三个用户来说，这个默认value都分别适配他们三种分辨率。

**Comment by WFCN** [comment]
其实是这样  假如用楼主的这个全的values值得话   如果市面上出现一款特殊分辨率的手机
比如1920*1081  ,这个系统会自动向下找  这样就找到了1920*1080了   除非有一款手机分辨率低于
480*320的话 这样才会走默认的values   所以默认values换成dp的作用其实就是预览使用的......当然换成px更精确  但是预览时就不好玩儿了

**Comment by JGNS** [comment]
@WFCN  懂了，老铁，非常感谢！既然都能匹配最接近的values文件夹，那其实出现了特殊的分辨率问题也不大，现在手机都挺统一了，不会出现什么跳跃性的分辨率，是么

**Comment by WFCN** [comment]
@JGNS 现在已经换了适配方式了用的sw方式 values这种方式 真的差距大  可以加我qq1761863342
